Source/cryptography/Cryptography.cpp, Source/cryptography/Cryptography.vcxproj, Source/cryptography/Cryptography.vcxproj.filters, Source/cryptography/ICryptography.h, Source/cryptography/implementation/OpenSSL/Cipher.cpp, Source/cryptography/implementation/OpenSSL/DiffieHellman.cpp, Source/cryptography/implementation/OpenSSL/Hash.cpp, Source/cryptography/implementation/OpenSSL/Vault.cpp, Source/cryptography/implementation/SecApi/Cipher.cpp, Source/cryptography/implementation/SecApi/Cipher.h, Source/cryptography/implementation/Thunder/Cipher.cpp, Source/cryptography/implementation/cipher_implementation.h
This prepares the OpenSSL implementation to work with the latest interface (OpenSSL1.1) it is also preparred to be compiled and used in a windows environment.
=> [OPENSSL] Upgrade to OpenSSL 1.1 and make it compilable on windows.

Source/compositorclient/Client.h, Source/compositorclient/Wayland/Implementation.h, Source/compositorclient/Wayland/Weston.cpp
This pull request adds a new API GetNativeSurface() to the Weston wayland compositor client code. This is used by wpebackend-rdk to obtain the webkit browser surface created by Thunder (see pull request here https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/pull/55).
The reason for adding this api, is so that we can use GStreamer waylandsink as the video sink in wpewebkit (instead of westeros sink). For this to function correctly GStreamer backend in wpewebkit needs to set an external surface (the one created by Thunder), so that the video surface is correctly created as a sub-surface of the browser.
The following video demonstrates this which shows Widevine EME playback using OP-TEE, using Weston compositor, Thunder/wpeframework and OpenCDM, plus webkit using waylandsink as the …
=> Weston: waylandsink: Add GetNativeSurface() api

Source/compositorclient/Client.h, Source/compositorclient/RPI/Implementation.cpp, Source/compositorclient/Wayland/Implementation.h, Source/compositorclient/Wayland/Weston.cpp
Re-worked previous implementation a bit following Pierres review
feedback to better map to the existing IDisplay & ISurface classes.
SurfaceByName() is used on the IDisplay class to get the ISurface.
NativeSurface() is used on the ISurface to get the native surface.
These api's are used with Wayland Weston compositor client when
using waylandsink as the video sink in webkit. I've moved the implementation
to the Implementation.h header which is shared between Westeros and Weston.
wpebackend-rdk calls these apis to obtain the surface handle created by
Thunder, which is then passed to waylandsink as an external surface so
that the video surface is correctly created as a sub-surface
of the browser.
Also RPI compositorclient is updated to have a stub implementation.
Signed-off-by: Peter …
=> compositorclient: add SurfaceByName() and NativeSurface() apis

Source/cryptography/implementation/SecApi/VaultNetflix.cpp
For cases where SOC specific Netflix MGK Backend is use, boundkey msg file is not required. If file is prsent that content will be passed. If file is not present empty buffer is passed, which will be ignored by SOC  Secapi-Netflix library.
=> Send empty buffer on no boundkey file present case

Source/ocdm/Module.h, Source/ocdm/open_cdm.cpp, Source/ocdm/open_cdm_impl.h
- Reason for change :  Improvement, memory leak fix
The method:
static OpenCDMAccessor* Instance()
is currently casuing a memory leak of this instance.
- Solution :
Suggest to instantiate a OCDMAccessor through lazy creation in order to
get "properly" destructed on app closure.
As an improvement, use variadic template in Singleton implementation.
=> [METRO-143] ocdm client instance creation

Source/displayinfo/DisplayInfo.cpp, Source/displayinfo/display_info/main.c, Source/displayinfo/include/displayinfo.h
Used SmartInterfaceType so that upon plugin deactivation the retrieved instance is in a nonoperational state, meaning that any function call inside the client app will not succeed. Upon activation, in the implementation, the new interface will be accessed. The client however always has the valid pointer, which points to the implementation class. 
Added functionality of callbacks when instance changes its operational state. Renamed register and unregister methods for a callback so they easily differ.
Functions now return uint32_t, which is used for returning Core::Errors. Result parameters are retrieved via pointer argument.
=> [DisplayInfo] Added automatic reconnection, changed interfaces. 

Source/cryptography/implementation/SecApi/Cipher.cpp, Source/cryptography/implementation/SecApi/CipherNetflix.cpp, Source/cryptography/implementation/SecApi/DiffieHellman.cpp
Missing semicolon causes SecApi/Cipher.cpp to fail to compile when
debug build is enabled. On release there is no problem as ASSERT()
evaluates to nothing and thus semicolon is not really needed.
Signed-off-by: Michał Łyszczek <michal.lyszczek@consult.red>
=> SecApi/Cipher.cpp: add missing ';' in ASSERT() call

Source/securityagent/ipclink.cpp
Reason for change: GetSecurityToken isn't thread safe.
Test Procedure: See no "status 3" in logs.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>
=> RDKTV-4805 : fix GetSecurityToken

Source/securityagent/CMakeLists.txt, Source/securityagent/sec_agent/CMakeLists.txt, Source/securityagent/sec_agent/main.cpp
The last backport of securityagent RPC change from R3 to R2 broke the
cmake. Add also a sec_agent test utility.
=> Fix the CMakeLists.txt file of securityagent

Source/ocdm/open_cdm.cpp
Step 3.4.3.1 and 3.4.3.3 of https://w3c.github.io/encrypted-media/#attempt-to-decrypt
There are issues observed in Amazon app when user enters into an asset details page and comes out of it quickly. This causes app to generate request but before the request is completed user leaves the asset forcing the app to close. This close doesn't succeed as the Session is not 'callable' yet. This leaves the session open and this remains in the WebKit & OpenCDMAccessor. When the same asset is played again, the current implementation (OpenCDMAccessor::WaitForKey) picks a random session for the given key and waits indefinitely for its status to be updated.
The patch tries to look at all the sessions which has the given key and returns the first one that is usable.
=> Check all available sessions for the given key and return any usable session if found

Source/ocdm/open_cdm.cpp
Step 3.4.3.1 and 3.4.3.3 of https://w3c.github.io/encrypted-media/#attempt-to-decrypt
There are issues observed in Amazon app when user enters into an asset details page and comes out of it quickly. This causes app to generate request but before the request is completed user leaves the asset forcing the app to close. This close doesn't succeed as the Session is not 'callable' yet. This leaves the session open and this remains in the WebKit & OpenCDMAccessor. When the same asset is played again, the current implementation (OpenCDMAccessor::WaitForKey) picks a random session for the given key and waits indefinitely for its status to be updated.
The patch tries to look at all the sessions which has the given key and returns the first one that is usable.
=> Check all available sessions for the given key and return any usable session

Source/provisionproxy/ipclink.cpp
Use different declaration macro because ProvisionProxy is built as an archive. See also: https://github.com/rdkcentral/Thunder/pull/715
=> [ProvisionProxy] Define MODULE_NAME in archive

Source/ocdm/adapter/broadcom-svp-secbuf/open_cdm_adapter.cpp, Source/ocdm/adapter/gstreamer/open_cdm_adapter.cpp, Source/ocdm/adapter/open_cdm_adapter.h, Source/ocdm/open_cdm.cpp, Source/ocdm/open_cdm.h, Source/ocdm/open_cdm_impl.h
The old decrypt API will try to fetch the pattern and scheme from Protection
metadata and call v2.
=> Add a new version 2 of decrypt API to pass in Encryption Scheme and pattern

cmake/FindGBM.cmake
Changes in the meta-wpe [patch](https://github.com/WebPlatformForEmbedded/meta-wpe/blob/main/recipes-wpe/wpeframework/wpeframework-clientlibraries/0001-cmake-become-more-easy-in-findgbm.patch) is added
=> ThunderClient: Find GBM: changes in meta-wpe patch added

Source/cryptography/Cryptography.cpp, Source/cryptography/ICryptography.h, Source/cryptography/implementation/OpenSSL/Cipher.cpp, Source/cryptography/implementation/SecApi/Cipher.cpp, Source/cryptography/implementation/SecApi/Cipher.h, Source/cryptography/implementation/SecApi/CipherNetflix.cpp, Source/cryptography/implementation/Thunder/Cipher.cpp, Source/cryptography/implementation/cipher_implementation.h
This aligns with the R3 implementation and allows Decrypt/Encrypt
methods to return error through a negative values.
=> Allow error reporting for Decrypt/Encrypt methods

Source/compositorclient/RPI/CMakeLists.txt, Source/virtualinput/CMakeLists.txt
Fix to solve the issue: /usr/lib/libcompositorclient.so.1: undefined symbol: VirtualInput with warning reporting enabled.
=> CompositorClient:RPI: set include path

Source/displayinfo/DisplayInfo.cpp
Fix a bug where instead of proper memory, a success/failiure status
was returned.
=> Return correct GPU memory, not the method status

Source/displayinfo/DisplayInfo.cpp
Upstreaming a patch from a customer environment:
Ensure that DisplayInfoAdministration::Delete() closes the COM channel when removing the last client instance in the list. The COM channel is opened by DisplayInfoAdministration::Instance() when creating the first client instance so, to keep the implementation symmetrical, it should conversely also close it when removing the last client instance. Without this, and because the DisplayInfoAdministration instance is static, the COM channel was only being closed by the DisplayInfoAdministration destructor, called in the context of the C library destructors invoking. However, at this point, closing if the COMchannel has undefined behavior because Thunder objects on which the channel closing depends have already been destructed. For instance, for …
=> Close COM channel when last instance is deleted

CMakeLists.txt
Reason for change: Bumped libraries version to 2.1.11
Test Procedure: Build and verify.
Risks: Low
Signed-off-by:Zameerun Rasheed M S <zexpen@gmail.com>
=> RDK-37251: Thunder R2-v1.11 upgrade (Bug Fixes)

Source/cryptography/implementation/OpenSSL/Cipher.cpp, Source/cryptography/implementation/OpenSSL/Hash.cpp, Source/cryptography/implementation/OpenSSL/Vault.cpp
Reason for change: fixes the crash observed in Cryptography test suite Test Procedure: Build and verify.
Risks: Low
Note : Change taken from accelerator device
Signed-off-by: Vijith T V <vijith.tv@ltts.com>
=> BCM72180-247: There is a common fix needed in ThunderClientLibraries

Source/compositorclient/RPI/CMakeLists.txt
Broken by target name change in [5aca10](https://github.com/rdkcentral/ThunderClientLibraries/commit/5aca10)
=> Fixing libdrm target name in compositorclient/RPI/CMakeLists.txt

CMakeLists.txt, Source/cryptography/implementation/OpenSSL/DiffieHellman.cpp, Source/cryptography/implementation/OpenSSL/Hash.cpp, Source/cryptography/implementation/OpenSSL/Vault.cpp, Source/ocdm/CMakeLists.txt
@pwielders do we want to disable pedantic warnings around the zero-sized array declaration like I did, or maybe it would be better to somehow change it?
=> [Warnings] Adding pedantic warnings and treating all warnings as errors, fixing warnings

.github/workflows/Build ThunderClientLibraries on Linux.yml, .github/workflows/Linux build template.yml
Same as with the Thunder PR: https://github.com/rdkcentral/Thunder/pull/1496
This is an initial pull request - the new workflows have to be called from my branches for now (there is a dependency between the workflows), since we need to first merge new templates in each repo. Then, I'll make one more set of pull requests to redirect this new feature to master branches of our repos.
Required checks got updated to the new ones by Stephen.
=> [Actions] Managing dependencies to make the workflows callable from different repos

.github/workflows/Build ThunderClientLibraries on Linux.yml
The last set of pull requests, now the new Actions will use workflows from our repos instead of my forks, which sadly couldn't have been done in one go.
=> [Actions] Using the already merged workflows instead of my forks

Source/ocdm/CMakeLists.txt, Source/ocdm/adapter/gstreamer/open_cdm_adapter.cpp, Source/ocdm/adapter/open_cdm_adapter.h, Source/ocdm/ocdm.vcxproj, Source/ocdm/open_cdm.cpp, Source/ocdm/open_cdm_ext.cpp, Source/ocdm/open_cdm_impl.cpp, Source/ocdm/open_cdm_impl.h
Session private data like SVP hardware specific context can be constructed and associated with a OCDM Session.
=> [OCDM] Add functionality to construct Session private data.

.github/workflows/Build ThunderClientLibraries on Linux.yml, .github/workflows/Linux build template.yml
A while ago someone noticed a compilation error with Cryptography locally, and we decided it is worth to try to add it into Actions, so this Jira ticket was created: https://jira.rdkcentral.com/jira/browse/METROL-1033
Originally, over a year ago, it was not possible due to some compilation errors, but it looks like it has been long resolved. So, after making sure correct libraries are installed and linked for both 32-bit and 64-bit, Cryptography with OpenSSL implementation is now built in the Linux actions.
=> [Actions] Adding Cryptography with OpenSSL implementation to be built on Linux

.github/workflows/Build ThunderClientLibraries on MacOS.yml
Otherwise it clashes with the Linux required checks, even despite the workflow name being different
=> [Actions] Make sure all MacOS job names are unique

Source/graphicsbuffer/include/graphicsbuffer/GraphicsBufferType.h
Hiding GCC 14.2 warnings that become errors, checked it with @MFransen69 and this was the best for now.
=> add DISABLE_WARNING_OVERLOADED_VIRTUALS
